### ISSUE TITLE
suggestion for input of action node

### ISSUE THREAD

**Issue by darkoddio** [lopelex/node-red-contrib-harmony#1]
hi
I'm using v1.0.7 and I have a suggestion for you
for the activity node, why don't fire the activity with payload true/1/on and simply send the poweroff command when payload is false/0/off?

**Comment by lopelex** [comment]
https://github.com/lopelex/node-red-contrib-harmony/commit/32bd7fce66f615f90ae3db0cc1fa070afe6c0b15

**Comment by lopelex** [comment]
nmp install https://github.com/lopelex/node-red-contrib-harmony.git

**Comment by lopelex** [comment]
publish version 1.0.8
