### ISSUE TITLE
'Hold' command not working

### ISSUE THREAD

**Issue by BenJEAR** [lopelex/node-red-contrib-harmony#12]
Hi, I can't seem to get the 'hold time' function to work in a command node. I have a panasonic TV that needs 'PowerOn' to be held down for maybe half a second for the tv to actually come on. I've assumed hold time is in milliseconds and increased to>1000,  but the tv light only blinks as if a regular 'pressrelease' command is being sent. I'm a complete noob when it comes to Java (although digging in to this issue is acting as a nice learning curve). Anyone else having this problem, or any ideas what might be the cause?
Thanks
Ben

p.s. should probably add that all other functions appear to work perfectly. Amazing bit of work, thanks!

**Comment by lopelex** [comment]
try version 2.2.3

**Comment by BenJEAR** [comment]
Hi, Thanks but the pallete manager in Node Red is still pointing to v2.2.1, with no option to update..?

**Comment by BenJEAR** [comment]
OK, I uninstalled and re-installed the '...contrib-harmony' node, which looks to have updated 'harmony-websocket' to version to 1.5.2. and the hold function appears to be working now 👍 ( I can see the change to the sendCommandWithDelay function in Harmony-Websocket.js) however '...contrib-harmony is still says it's on v2.2.1.

Anyway, it's working, so thank you very much!

**Comment by lopelex** [comment]
Cool
