### ISSUE TITLE
2.2.4 not listed in Node Red module list

### ISSUE THREAD

**Issue by hoeni** [lopelex/node-red-contrib-harmony#16]
Since I was hit by #15 I was waiting for version 2.2.4 to finally become installable inside Node Red, but it still doesn't show up 2 weeks after publication.

Does this need some special push or registration to make this version available to be installable from node red itself?
When using Node Red's Web GUI to install it still shows me the 2.2.3 as latest.
Also on https://flows.nodered.org/node/node-red-contrib-harmony-websocket it shows version 2.2.3 (however the badge shows 2.2.4, but I suppose thats an independent link).

**Comment by hoeni** [comment]
Thank you, now it works. Just for my curiosity: What was missing?

**Comment by ristomatti** [comment]
@hoeni See my reply to you here: #15.

**Comment by lopelex** [comment]
I requested a refresh on nodered.org.

**Comment by hoeni** [comment]
Haha, now I can see it in my Redmatic, but it fails install due to gyp issues (but thats not a problem for here) 🙈
Thanks anyway!
