### ISSUE TITLE
Merge required when I change anything

### ISSUE THREAD

**Issue by raspberrypi4-docker** [lopelex/node-red-contrib-harmony#3]
Have installed and looks really promising... but whenever I change any other node I get this error.

![image](https://user-images.githubusercontent.com/52397834/60847392-e0c4e300-a225-11e9-82f6-0e8be124f2b8.png)

**Comment by DandyDiamond** [comment]
Have the same problem on RaspberryPi.

Node-RED version: v0.20.7
Node.js  version: v10.16.0
Linux 4.19.57-v7+ arm LE

HTH

**Comment by lopelex** [comment]
Can not reproduce the error unfortunately.
Need more information.

**Comment by DandyDiamond** [comment]
Before complete system rebuild, from scratch with new images, last week with up to date versions, all was running fine.  Sorry, can't tell you which versions were running before.

Rebuild SD card image and fresh install of Node-Red as per Node-Red instructions.
Required Nodes installed through Palette.

Message comes up after minutes that the 'Server is running a more recent set of Flows'
No interaction required.
After Deploy, Editor page would always display first flow.

Did this twice before investigating further.

Hardware
Raspberry Pi 2B

Node-Red details
Welcome to Node-RED
===================
25 Jul 06:37:14 - [info] Node-RED version: v0.20.7
25 Jul 06:37:14 - [info] Node.js  version: v10.16.0
25 Jul 06:37:14 - [info] Linux 4.19.57-v7+ arm LE
25 Jul 06:37:16 - [info] Loading palette nodes
25 Jul 06:37:28 - [info] Dashboard version 2.15.5 started at /ui
25 Jul 06:37:29 - [info] Settings file  : /home/pi/.node-red/settings.js
25 Jul 06:37:29 - [info] Context store  : 'default' [module=memory]
25 Jul 06:37:29 - [info] User directory : /home/pi/.node-red
25 Jul 06:37:29 - [warn] Projects disabled : editorTheme.projects.enabled=false
25 Jul 06:37:29 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
25 Jul 06:37:29 - [info] Server now running at http://127.0.0.1:1880/

Flows and node-red-contrib-harmony-websocket removed - after several attempts had to remove node manually.
System running as expected.
Comment raised on GitHub under similar Issue.

Received response from lopelex

Re-installed harmony-websocket
System now appears to be running fine.

Two days later and the error message re-appears.

HTH

**Comment by nodecentral** [comment]
I’d just like to add to this as I had the same problem - and have been troubleshooting the same issue - see thread here.

https://discourse.nodered.org/t/recurring-the-flows-on-the-server-have-been-updated-message/13885/50

Uninstalling the harmony addon resolved it.

**Comment by bakman2** [comment]
[Last commit](https://github.com/lopelex/node-red-contrib-harmony/commit/a6e8107a03e6c03295aa016cee08cabd28bae6c1): 8-Jul, first issue reported: 9-Jul. Is the test in the commit correct or does it always reload the config ?

**Comment by nodecentral** [comment]
Just to update that installing the 1.0.8 version does not generate any of the update/merge messages. The issue is definitely with the latest one.

**Comment by lopelex** [comment]
find the bug in https://github.com/lopelex/node-red-contrib-harmony/blob/master/harmony/harmony-server.js#L58
