### ISSUE TITLE
possible to have 2 hubs?

### ISSUE THREAD

**Issue by stoneobscurity** [lopelex/node-red-contrib-harmony#5]
when i try to add a second hub, there seems to be only one config node. i can either set the config node to hub A or hub B, then all the nodes use that hub. is there a way to add a second config node?

**Comment by ristomatti** [comment]
@stoneobscurity Have you tried creating a new config node for the second hub?

**Comment by lopelex** [comment]
![Bildschirmfoto 2019-09-04 um 17 58 01](https://user-images.githubusercontent.com/577670/64271458-a46be580-cf3d-11e9-8cce-d89ed30d1f84.png)

Try to create an new server using the option in the server dropdown menu.
