### ISSUE TITLE
[question] Retrieve Play/Pause/Stop

### ISSUE THREAD

**Issue by RaymondMouthaan** [lopelex/node-red-contrib-harmony#6]
Hello,

I was wondering if it would be possible to get more info from the HarmonyHub (observe), like play/pause/stop? Currently I am using Observe to get info about the Activities, but it would be great if also status like play/pause and stop could be retrieved. 

Greets,
Ray

**Comment by lopelex** [comment]
Unfortunately, I have not found a way to get this information.

**Comment by RaymondMouthaan** [comment]
> Unfortunately, I have not found a way to get this information.

Sadly, I did not either .. i suppose the Harmony API only exposes activity info and commands, but not detail info about the activity like play, pause and stop. :(
