### ISSUE TITLE
[Feature request] Commands via msg.payload 

### ISSUE THREAD

**Issue by bakman2** [lopelex/node-red-contrib-harmony#7]
It would add a lot of flexibility if one could send the command via `msg.payload` instead of separate nodes. Like a pulldown option `--set via msg.payload--`

Then one could use eg;  
```
// sequence
node.send({payload:"Power"}}
node.send({payload:"HDMI1"}}
node.send({payload:"Guide"}}
node.send({payload:"Down"}}
...
```
Where payload should match the available commands.
Delay could be controlled with a delay node. 

I like this node a lot but sequence programming or controlling from a different source is a pain.

**Comment by lopelex** [comment]
try this: 
https://github.com/lopelex/node-red-contrib-harmony/commit/6084b164fcd31948cd5e3d786d6208aee293eb20
npm install https://github.com/lopelex/node-red-contrib-harmony.git

**Comment by lopelex** [comment]
Also improved command node input handling.
https://github.com/lopelex/node-red-contrib-harmony/blob/a830d9438662692f32e802c6849700dc6c62bdc8/nodes/command.js#L33
Now you can send objects like:
`{"command":"Mute","deviceId":"53280812"}`
or preselect an activity and send:
`{"command":"Mute"}`

**Comment by bakman2** [comment]
Fantastic stuff, thanks a lot!

**Comment by MattL0** [comment]
hi . is there a way to send multiple command (same and diff) in the json with delay option and count?
