### ISSUE TITLE
 Can't find any Hub

### ISSUE THREAD

**Issue by nicedevil007** [lopelex/node-red-contrib-harmony#8]
Hey guys,

I have a small problem to get this nodes to work well.

First things first: The setup I'm using is a raspberry pi 4 in the same network as the harmony hub is. The raspberry is a docker host with node-red. The node-red network is not the hosts network.

I can enter the IP Adress of my hub manually like this way:

![image](https://user-images.githubusercontent.com/17103076/70863988-25c81080-1f4e-11ea-95c7-d3168178fca4.png)

Everything is working with this but after a restart of node-red the connection is lost and I have to change the IP Adress manually to another one and then deploy and change the IP Adress back. 
The automatic search method isn't working on my setup. In my opinion that is the main reason why the connection won't work after a restart of node-red or something like this.

And that is maybe because of missing portforward to the node-red network from the docker host. 

Do you know which port is used for the automatic search? (I guess you do ;).

Thank you in advance

**Comment by lopelex** [comment]
The discovery of the hub runs via ssdp. Should run over port 1900. Communication to the hub runs on port 8088.

**Comment by lopelex** [comment]
Did you get it going?

**Comment by nicedevil007** [comment]
Nope not on this way, but friend told me, that I'm able to give the hosts IP Adress to harmony while searching my "host's network" for devices. That fixed some discovering issue's on his setup. While I don't know where he set it up, I have to be a bit more patient :)

For now it just works if the harmony and node-red is in the same network and node-red isn't in its own docker network.

**Comment by Pepe962** [comment]
I have been having this same problem for the past few months

**Comment by lopelex** [comment]
Please turn on the debug option. Now you can maybe find something in the log.
![Screenshot_20200314-192103_Chrome](https://user-images.githubusercontent.com/577670/76688037-850aef00-6629-11ea-9103-6336c9f5ce1e.jpg)

**Comment by lopelex** [comment]
![20200314_192846](https://user-images.githubusercontent.com/577670/76688110-298d3100-662a-11ea-8543-2564fea7f617.jpg)
